name: Prebuild for Windows (Electron ABI 133)

on:
  push:
    tags:
      - 'v*'  # sproži na tagu, npr. v0.1.0

jobs:
  build-windows:
    name: Build on Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install build tools & dependencies
        run: |
          npm install -g node-gyp prebuild
          npm ci

      - name: Prepare binding directory for prebuild
        run: |
          $abi = "v133"
          $platform = "win32"
          $arch = "x64"
          $bindingPath = "lib/binding/$abi-$platform-$arch"
          mkdir $bindingPath -Force
          copy build\Release\pcsclite.node "$bindingPath\pcsclite.node"

      - name: Prebuild for Electron ABI 133 (Electron 30)
        run: |
          prebuild -r electron -t 30 --arch x64 --platform win32 --strip

      - name: List prebuilt output
        run: dir ./prebuilds/*.tar.gz || echo "No .tar.gz found"

      - name: Upload prebuilt binary
        uses: actions/upload-artifact@v4
        with:
          name: pcsclite-electron-v133-win32-x64
          path: ./prebuilds/*.tar.gz

  release:
    name: Publish GitHub Release
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pcsclite-electron-v133-win32-x64
          path: ./artifacts

      - name: Publish release with binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Prebuilt pcsclite for Electron ABI 133
          files: ./artifacts/*.tar.gz
